spring.application.name=api-assessment

server.port=${DEFAULT_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt-key=${JWT_KEY}
app.jwt-expiration=${JWT_EXPIRATION}

